import JammaLean

/-! Prints the axioms each headline theorem depends on. Every line must list only
`propext`, `Classical.choice` and `Quot.sound`; `sorryAx` means an unfinished proof. -/

#print axioms JammaLean.abIndex_image
#print axioms JammaLean.abIndex_comm
#print axioms JammaLean.pab_succ
#print axioms JammaLean.resid_spec
#print axioms JammaLean.resid_unique
#print axioms JammaLean.pab_eq_inner_resid_left
#print axioms JammaLean.hMat_inv
#print axioms JammaLean.quad_form_rotated
#print axioms JammaLean.logdet_hMat
#print axioms JammaLean.pab_row0_eq_dense
#print axioms JammaLean.px_yy_eq
#print axioms JammaLean.waldF_eq_beta_sq_div_var
#print axioms JammaLean.waldF_eq_r2
#print axioms JammaLean.scoreF_eq_r2
#print axioms JammaLean.scoreF_le_n
#print axioms JammaLean.waldF_nonneg
#print axioms JammaLean.complement_z
#print axioms JammaLean.gaussLogL_le_profiled
#print axioms JammaLean.gaussLogL_at_argmax
#print axioms JammaLean.gaussLogL_argmax_unique
#print axioms JammaLean.logdetKernel_eq_sum_log
#print axioms JammaLean.kinship_posSemidef
#print axioms JammaLean.eigen_nonneg
#print axioms JammaLean.hpos_of_kinship
#print axioms JammaLean.logdet_hMat_kinship
#print axioms JammaLean.pab_row0_eq_dense_kinship
#print axioms JammaLean.kinship_mulVec_one
#print axioms JammaLean.mleLogL_H0_le_H1
#print axioms JammaLean.lrt_nonneg
#print axioms JammaLean.lrt_stat_nonneg
#print axioms JammaLean.frexpExp_eq
#print axioms JammaLean.frexpBits_eq
#print axioms JammaLean.frexpBits_isPosNormal
#print axioms JammaLean.frexpBits_split
#print axioms JammaLean.frexpBits_hsplit
#print axioms JammaLean.prod_pab_diag_eq_det_gram
#print axioms JammaLean.sum_log_pab_diag_eq_log_det_gram
#print axioms JammaLean.gram_weighted_rot_eq
#print axioms JammaLean.gram_rot_eq
#print axioms JammaLean.logdet_hiw_eq
#print axioms JammaLean.resid_eq_closedForm
#print axioms JammaLean.pab_eq_closedForm
#print axioms JammaLean.covGram_isUnit_det
#print axioms JammaLean.pab_eq_matrix_closedForm
#print axioms JammaLean.pab_rotated_eq_closedForm
#print axioms JammaLean.contrast_inv_eq_projP
#print axioms JammaLean.contrast_quad_eq_pyy
#print axioms JammaLean.contrast_complete
#print axioms JammaLean.det_contrast
#print axioms JammaLean.remlLogL_eq_contrast
#print axioms JammaLean.contrastLogL_le_remlLogL
#print axioms JammaLean.contrastLogL_at_argmax
#print axioms JammaLean.contrast_centered_kinship
#print axioms JammaLean.contrastLogL_centered
#print axioms JammaLean.remlLogL_centered
#print axioms JammaLean.remlLogL_eq_contrast_df
#print axioms JammaLean.exists_contrast_basis
#print axioms JammaLean.remlLogL_centering_invariant
#print axioms JammaLean.pab_eq_schur
#print axioms JammaLean.det_gram_eq_prod
#print axioms JammaLean.pab_eq_projP
#print axioms JammaLean.remlLogLPab_eq
#print axioms JammaLean.remlLogLPab_eq_contrast
#print axioms JammaLean.pab_congr_of_inner
#print axioms JammaLean.inner_rotated_eq
#print axioms JammaLean.pab_rotated_eq
#print axioms JammaLean.pab_rotated_embedCols_eq
#print axioms JammaLean.logdet_rotated_eq
#print axioms JammaLean.signFlip_eigen
#print axioms JammaLean.pab_signFlip_eq
#print axioms JammaLean.logdet_signFlip_eq
#print axioms JammaLean.kinship_submatrix
#print axioms JammaLean.kinship_select_after_centre
#print axioms JammaLean.kinship_eq_sum_blocks
#print axioms JammaLean.kinship_eq_append

-- `abIndex` is computable: the packed slots for n_cvt = 1 (cols = 3), in the
-- order `build_index_table` walks them.
#eval (List.range 3).flatMap fun k => (List.range' k (3 - k)).map fun j =>
  (k + 1, j + 1, JammaLean.abIndex 3 (k + 1) (j + 1))
#print axioms JammaLean.pow_sub_one_le_fpGamma
#print axioms JammaLean.fpGamma_mono
#print axioms JammaLean.abs_prod_sub_one_le_fpGamma
#print axioms JammaLean.fsum_err_le_fpGamma
#print axioms JammaLean.fdot_err_le_fpGamma
#print axioms JammaLean.fkin_err_le_fpGamma
#print axioms JammaLean.fwdot_err_le_fpGamma
#print axioms JammaLean.fwdot_err_le_fpGamma_of_nonneg
#print axioms JammaLean.fpGamma_float64_kinship
#print axioms JammaLean.fpGamma_float64_pab
#print axioms JammaLean.grid_bracket_mem
#print axioms JammaLean.gsStepC_eq
#print axioms JammaLean.gs_iterate_inv
#print axioms JammaLean.gs_iterate_width
#print axioms JammaLean.golden_error
#print axioms JammaLean.grid_golden_error
#print axioms JammaLean.golden_error_code
#print axioms JammaLean.probes_mem
#print axioms JammaLean.newtonLoop_mem
#print axioms JammaLean.lambdaSearch_error
#print axioms JammaLean.lambdaSearch_error_of_not_interior
#print axioms JammaLean.refine_error_code
#print axioms JammaLean.newton_step_toward_root
#print axioms JammaLean.accepted_closer_of_same_side
#print axioms JammaLean.newtonLoop_affine
#print axioms JammaLean.refine_can_leave_golden_bracket
#print axioms JammaLean.STree.err_le_pow
#print axioms JammaLean.STree.err_le_fpGamma
#print axioms JammaLean.STree.err_le_fpGamma_length
#print axioms JammaLean.STree.depth_lt_length
#print axioms JammaLean.STree.fdot_err_le_fpGamma
#print axioms JammaLean.STree.fkin_err_le_fpGamma
#print axioms JammaLean.STree.fwdot_err_le_fpGamma
#print axioms JammaLean.STree.fkin_err_float64
#print axioms JammaLean.STree.fwdot_err_float64
#print axioms JammaLean.STree.sum_abs_mul_le_norm
#print axioms JammaLean.STree.fdot_err_le_fpGamma_norm
#print axioms JammaLean.two_impl_le
#print axioms JammaLean.resid_eq_zero_iff
#print axioms JammaLean.pab_self_eq_zero_iff
#print axioms JammaLean.pab_self_le_zero_iff
#print axioms JammaLean.pab_self_pos_iff
#print axioms JammaLean.pab_eq_zero_of_mem_left
#print axioms JammaLean.pab_smul_intercept_eq_zero
#print axioms JammaLean.pab_pivot_eq_zero_iff
#print axioms JammaLean.pivots_pos_iff_linearIndependent
#print axioms JammaLean.linearIndependent_iff_not_mem_covSpan
#print axioms JammaLean.isUnit_det_covGram_iff_pivots_pos
#print axioms JammaLean.sum_log_pab_diag_of_linearIndependent
#print axioms JammaLean.pab_eq_closedForm_of_linearIndependent
#print axioms JammaLean.resid_eq_closedForm_of_linearIndependent
#print axioms JammaLean.log_det_gram_of_linearIndependent
#print axioms JammaLean.pab_eq_schur_of_linearIndependent
#print axioms JammaLean.logdet_hiw_eq_of_linearIndependent
#print axioms JammaLean.pab_succ_eq_calcPabStep
#print axioms JammaLean.hasDerivAt_calcPabStep_ww
#print axioms JammaLean.hasDerivAt_calcPabStep_aw
#print axioms JammaLean.hasDerivAt_calcPabStep_bw
#print axioms JammaLean.hasDerivAt_calcPabStep_ab
#print axioms JammaLean.calcPabStep_perturb
#print axioms JammaLean.calcPabStep_perturb_ww
#print axioms JammaLean.calcPabStep_perturb_le
#print axioms JammaLean.abs_pab_le_sqrt_mul_sqrt
#print axioms JammaLean.pab_step_perturb_le
#print axioms JammaLean.incBeta_one
#print axioms JammaLean.fTail_eq_incBeta
#print axioms JammaLean.fTail_zero
#print axioms JammaLean.fPDF_antitoneOn
#print axioms JammaLean.fTail_antitoneOn
#print axioms JammaLean.fTail_lipschitzOn
#print axioms JammaLean.tendsto_fPDF_zero
#print axioms JammaLean.fTail_not_lipschitzOn
#print axioms JammaLean.two_gaussian_tail_eq_erfc
#print axioms JammaLean.gaussian_sq_tail
#print axioms JammaLean.chiSq1_tail_eq_erfc
#print axioms JammaLean.erfc_antitone
#print axioms JammaLean.erfc_sqrt_half_antitone
#print axioms JammaLean.chiSq1_tail_antitone
#print axioms JammaLean.erfc_sqrt_half_not_lipschitzOn
#print axioms JammaLean.coercive_mulVec
#print axioms JammaLean.det_ne_zero_of_coercive
#print axioms JammaLean.inv_opNorm_le_of_coercive
#print axioms JammaLean.matrix_inv_sub_inv
#print axioms JammaLean.resolvent_perturb
#print axioms JammaLean.dot_inv_perturb
#print axioms JammaLean.hpos_of_coercive
#print axioms JammaLean.pab_row0_perturb
#print axioms JammaLean.abs_log_det_le
#print axioms JammaLean.neg_log_one_sub_le
#print axioms JammaLean.logdet_perturb
#print axioms JammaLean.logdet_rotated_perturb
#print axioms JammaLean.rotated_quad_eq
#print axioms JammaLean.hMat_mul_rotatedInv
#print axioms JammaLean.rotatedInv_sub_inv
